[2024-07-19T07:30:06.694+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:30:05.226416+00:00 [queued]>
[2024-07-19T07:30:06.707+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:30:05.226416+00:00 [queued]>
[2024-07-19T07:30:06.707+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-19T07:30:06.727+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_compare_links> on 2024-07-19 07:30:05.226416+00:00
[2024-07-19T07:30:06.732+0000] {standard_task_runner.py:60} INFO - Started process 308 to run task
[2024-07-19T07:30:06.738+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawling_dag_v2', 'read_s3_and_compare_links', 'manual__2024-07-19T07:30:05.226416+00:00', '--job-id', '448', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmpjb87msip']
[2024-07-19T07:30:06.742+0000] {standard_task_runner.py:88} INFO - Job 448: Subtask read_s3_and_compare_links
[2024-07-19T07:30:06.808+0000] {task_command.py:423} INFO - Running <TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:30:05.226416+00:00 [running]> on host 9a455ef6c02c
[2024-07-19T07:30:06.904+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_dag_v2' AIRFLOW_CTX_TASK_ID='read_s3_and_compare_links' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T07:30:05.226416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T07:30:05.226416+00:00'
[2024-07-19T07:30:06.916+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T07:30:06.917+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T07:30:07.599+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/code_test/airflow_product_review.py", line 184, in read_s3_and_compare_links
    df = pd.read_csv(StringIO(obj['Body'].read().decode('utf-8-sig')))
  File "/usr/local/lib/python3.8/encodings/utf_8_sig.py", line 23, in decode
    (output, consumed) = codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 94: invalid start byte
[2024-07-19T07:30:07.614+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=crawling_dag_v2, task_id=read_s3_and_compare_links, execution_date=20240719T073005, start_date=20240719T073006, end_date=20240719T073007
[2024-07-19T07:30:07.642+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 448 for task read_s3_and_compare_links ('utf-8' codec can't decode byte 0xa4 in position 94: invalid start byte; 308)
[2024-07-19T07:30:07.676+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T07:30:07.748+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
