[2024-07-19T07:24:27.569+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:24:25.394683+00:00 [queued]>
[2024-07-19T07:24:27.582+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:24:25.394683+00:00 [queued]>
[2024-07-19T07:24:27.583+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-19T07:24:27.608+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_compare_links> on 2024-07-19 07:24:25.394683+00:00
[2024-07-19T07:24:27.619+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2024-07-19T07:24:27.623+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawling_dag_v2', 'read_s3_and_compare_links', 'manual__2024-07-19T07:24:25.394683+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmp7vqqcb1d']
[2024-07-19T07:24:27.627+0000] {standard_task_runner.py:88} INFO - Job 446: Subtask read_s3_and_compare_links
[2024-07-19T07:24:27.696+0000] {task_command.py:423} INFO - Running <TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:24:25.394683+00:00 [running]> on host 9a455ef6c02c
[2024-07-19T07:24:27.818+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_dag_v2' AIRFLOW_CTX_TASK_ID='read_s3_and_compare_links' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T07:24:25.394683+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T07:24:25.394683+00:00'
[2024-07-19T07:24:27.835+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T07:24:27.836+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T07:24:28.510+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/code_test/airflow_product_review.py", line 184, in read_s3_and_compare_links
    df = pd.read_csv(StringIO(obj['Body'].read().decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 94: invalid start byte
[2024-07-19T07:24:28.525+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=crawling_dag_v2, task_id=read_s3_and_compare_links, execution_date=20240719T072425, start_date=20240719T072427, end_date=20240719T072428
[2024-07-19T07:24:28.557+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 446 for task read_s3_and_compare_links ('utf-8' codec can't decode byte 0xa4 in position 94: invalid start byte; 220)
[2024-07-19T07:24:28.600+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T07:24:28.629+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
