[2024-07-19T07:35:12.134+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:30:07.248644+00:00 [queued]>
[2024-07-19T07:35:12.157+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:30:07.248644+00:00 [queued]>
[2024-07-19T07:35:12.157+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-19T07:35:12.180+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_compare_links> on 2024-07-19 07:30:07.248644+00:00
[2024-07-19T07:35:12.189+0000] {standard_task_runner.py:60} INFO - Started process 398 to run task
[2024-07-19T07:35:12.218+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawling_dag_v2', 'read_s3_and_compare_links', 'manual__2024-07-19T07:30:07.248644+00:00', '--job-id', '452', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmpk45g81ej']
[2024-07-19T07:35:12.234+0000] {standard_task_runner.py:88} INFO - Job 452: Subtask read_s3_and_compare_links
[2024-07-19T07:35:12.459+0000] {task_command.py:423} INFO - Running <TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T07:30:07.248644+00:00 [running]> on host 9a455ef6c02c
[2024-07-19T07:35:12.728+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_dag_v2' AIRFLOW_CTX_TASK_ID='read_s3_and_compare_links' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T07:30:07.248644+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T07:30:07.248644+00:00'
[2024-07-19T07:35:12.775+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T07:35:12.776+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T07:35:52.564+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-19T07:35:52.568+0000] {process_utils.py:131} INFO - Sending 15 to group 398. PIDs of all processes in the group: [398]
[2024-07-19T07:35:52.569+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 398
[2024-07-19T07:35:52.570+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-19T07:35:52.622+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=398, status='terminated', exitcode=0, started='07:35:11') (398) terminated with exit code 0
