[2024-07-20T05:18:02.305+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: crawling_dag_v3.read_s3_and_compare_links manual__2024-07-20T05:18:01.242332+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
