[2024-07-19T08:44:30.909+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T08:44:26.939661+00:00 [queued]>
[2024-07-19T08:44:30.934+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T08:44:26.939661+00:00 [queued]>
[2024-07-19T08:44:30.935+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-19T08:44:30.972+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_compare_links> on 2024-07-19 08:44:26.939661+00:00
[2024-07-19T08:44:30.984+0000] {standard_task_runner.py:60} INFO - Started process 1438 to run task
[2024-07-19T08:44:30.993+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawling_dag_v2', 'read_s3_and_compare_links', 'manual__2024-07-19T08:44:26.939661+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmp0md3yx02']
[2024-07-19T08:44:31.000+0000] {standard_task_runner.py:88} INFO - Job 465: Subtask read_s3_and_compare_links
[2024-07-19T08:44:31.165+0000] {task_command.py:423} INFO - Running <TaskInstance: crawling_dag_v2.read_s3_and_compare_links manual__2024-07-19T08:44:26.939661+00:00 [running]> on host 9a455ef6c02c
[2024-07-19T08:44:31.455+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_dag_v2' AIRFLOW_CTX_TASK_ID='read_s3_and_compare_links' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T08:44:26.939661+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T08:44:26.939661+00:00'
[2024-07-19T08:44:31.486+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T08:44:31.489+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T08:45:10.888+0000] {logging_mixin.py:188} INFO - Current number of unique href links: 43
[2024-07-19T08:45:21.566+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-07-19T08:45:21.569+0000] {process_utils.py:131} INFO - Sending 15 to group 1438. PIDs of all processes in the group: [1438]
[2024-07-19T08:45:21.569+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1438
[2024-07-19T08:45:21.570+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-19T08:45:21.584+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/code_test/airflow_product_review.py", line 208, in read_s3_and_compare_links
    href_links = get_href_links(driver, wait, actions, num_items_to_fetch=100)
  File "/opt/airflow/dags/code_test/airflow_product_review.py", line 26, in get_href_links
    element = wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 102, in until
    time.sleep(self._poll)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-07-19T08:45:21.590+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=crawling_dag_v2, task_id=read_s3_and_compare_links, execution_date=20240719T084426, start_date=20240719T084430, end_date=20240719T084521
[2024-07-19T08:45:21.615+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 465 for task read_s3_and_compare_links (Task received SIGTERM signal; 1438)
[2024-07-19T08:45:21.663+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1438, status='terminated', exitcode=1, started='08:44:30') (1438) terminated with exit code 1
