[2024-06-14T08:25:42.514+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_redshift_v3.ELT.data_extraction.upload_data_to_s3 manual__2024-06-14T08:25:36.754496+00:00 [queued]>
[2024-06-14T08:25:42.528+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_redshift_v3.ELT.data_extraction.upload_data_to_s3 manual__2024-06-14T08:25:36.754496+00:00 [queued]>
[2024-06-14T08:25:42.528+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-06-14T08:25:42.555+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ELT.data_extraction.upload_data_to_s3> on 2024-06-14 08:25:36.754496+00:00
[2024-06-14T08:25:42.574+0000] {standard_task_runner.py:57} INFO - Started process 832 to run task
[2024-06-14T08:25:42.578+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_redshift_v3', 'ELT.data_extraction.upload_data_to_s3', 'manual__2024-06-14T08:25:36.754496+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/test_redshift_real_v3.py', '--cfg-path', '/tmp/tmp6057c24i']
[2024-06-14T08:25:42.580+0000] {standard_task_runner.py:85} INFO - Job 247: Subtask ELT.data_extraction.upload_data_to_s3
[2024-06-14T08:25:42.648+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_s3_to_redshift_v3.ELT.data_extraction.upload_data_to_s3 manual__2024-06-14T08:25:36.754496+00:00 [running]> on host 9949536f6ac7
[2024-06-14T08:25:42.782+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_redshift_v3' AIRFLOW_CTX_TASK_ID='ELT.data_extraction.upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T08:25:36.754496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T08:25:36.754496+00:00'
[2024-06-14T08:25:42.801+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_redshift_real_v3.py", line 72, in upload_to_s3
    replace=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 115, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 86, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 734, in load_string
    bytes_data = string_data.encode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'
[2024-06-14T08:25:42.814+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_s3_to_redshift_v3, task_id=ELT.data_extraction.upload_data_to_s3, execution_date=20240614T082536, start_date=20240614T082542, end_date=20240614T082542
[2024-06-14T08:25:42.837+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 247 for task ELT.data_extraction.upload_data_to_s3 ('NoneType' object has no attribute 'encode'; 832)
[2024-06-14T08:25:42.876+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-06-14T08:25:42.926+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
