[2024-07-19T07:09:19.630+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag.read_s3_and_compare_links manual__2024-07-19T07:09:17.895011+00:00 [queued]>
[2024-07-19T07:09:19.642+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag.read_s3_and_compare_links manual__2024-07-19T07:09:17.895011+00:00 [queued]>
[2024-07-19T07:09:19.643+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-19T07:09:19.668+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_compare_links> on 2024-07-19 07:09:17.895011+00:00
[2024-07-19T07:09:19.675+0000] {standard_task_runner.py:60} INFO - Started process 2115 to run task
[2024-07-19T07:09:19.679+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag', 'read_s3_and_compare_links', 'manual__2024-07-19T07:09:17.895011+00:00', '--job-id', '441', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmpdibld1sw']
[2024-07-19T07:09:19.683+0000] {standard_task_runner.py:88} INFO - Job 441: Subtask read_s3_and_compare_links
[2024-07-19T07:09:19.739+0000] {task_command.py:423} INFO - Running <TaskInstance: crawl_dag.read_s3_and_compare_links manual__2024-07-19T07:09:17.895011+00:00 [running]> on host 46f973aa9339
[2024-07-19T07:09:19.864+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawl_dag' AIRFLOW_CTX_TASK_ID='read_s3_and_compare_links' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T07:09:17.895011+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T07:09:17.895011+00:00'
[2024-07-19T07:09:19.880+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T07:09:19.882+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T07:10:50.513+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-19T07:10:50.520+0000] {process_utils.py:131} INFO - Sending 15 to group 2115. PIDs of all processes in the group: [2115]
[2024-07-19T07:10:50.521+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2115
[2024-07-19T07:10:50.522+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-19T07:10:50.615+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2115, status='terminated', exitcode=0, started='07:09:19') (2115) terminated with exit code 0
