[2024-07-19T08:44:56.022+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:37:07.205922+00:00 [queued]>
[2024-07-19T08:44:56.041+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:37:07.205922+00:00 [queued]>
[2024-07-19T08:44:56.041+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-19T08:44:56.070+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_s3_and_add_size_color> on 2024-07-19 08:37:07.205922+00:00
[2024-07-19T08:44:56.079+0000] {standard_task_runner.py:60} INFO - Started process 1450 to run task
[2024-07-19T08:44:56.087+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crawling_dag_v2', 'read_s3_and_add_size_color', 'manual__2024-07-19T08:37:07.205922+00:00', '--job-id', '466', '--raw', '--subdir', 'DAGS_FOLDER/musinsa_dag.py', '--cfg-path', '/tmp/tmpoot88m4o']
[2024-07-19T08:44:56.091+0000] {standard_task_runner.py:88} INFO - Job 466: Subtask read_s3_and_add_size_color
[2024-07-19T08:44:56.179+0000] {task_command.py:423} INFO - Running <TaskInstance: crawling_dag_v2.read_s3_and_add_size_color manual__2024-07-19T08:37:07.205922+00:00 [running]> on host 9a455ef6c02c
[2024-07-19T08:44:56.370+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_dag_v2' AIRFLOW_CTX_TASK_ID='read_s3_and_add_size_color' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T08:37:07.205922+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T08:37:07.205922+00:00'
[2024-07-19T08:44:56.392+0000] {base.py:83} INFO - Using connection ID 'aws_s3' for task execution.
[2024-07-19T08:44:56.393+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T08:49:57.905+0000] {logging_mixin.py:188} INFO - Failed to visit https://www.musinsa.com/app/goods/2612829 due to Message: Could not start a new session. New session request timed out 
Host info: host: '6be934e86a63', ip: '172.19.0.4'
Build info: version: '4.22.0', revision: 'c5f3146703'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.146.1-microsoft-standard-WSL2', java.version: '17.0.11'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:221)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)
    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:360)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:128)
    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:87)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:360)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
    at org.openqa.selenium.grid.router.Router.execute (Router.java:87)
    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:360)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
    at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:360)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
    at java.util.concurrent.FutureTask.run (None:-1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
    at java.lang.Thread.run (None:-1)
[2024-07-19T08:50:24.492+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-19T08:50:24.500+0000] {process_utils.py:131} INFO - Sending 15 to group 1450. PIDs of all processes in the group: [1450]
[2024-07-19T08:50:24.501+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1450
[2024-07-19T08:50:24.502+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-19T08:50:24.504+0000] {logging_mixin.py:188} INFO - Failed to visit https://www.musinsa.com/app/goods/1191407 due to Task received SIGTERM signal
[2024-07-19T08:51:24.511+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=1450, name='airflow task ru', status='sleeping', started='08:44:55') did not respond to SIGTERM. Trying SIGKILL
[2024-07-19T08:51:24.513+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 1450
[2024-07-19T08:51:24.542+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1450, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='08:44:55') (1450) terminated with exit code -9
[2024-07-19T08:51:24.543+0000] {standard_task_runner.py:175} ERROR - Job 466 was killed before it finished (likely due to running out of memory)
